### PR TITLE
feat(fetch): support sparse checkout

### PR DESCRIPTION
**Pull request by MaineK00n**
## Motivation
Currently, `fetch redhat` involves clone/pull [aquasecurity/vuln-list](https://github.com/aquasecurity/vuln-list). If you have git installed, you can do a shallow clone like `$ git clone --depth=1`. However, since only `vuln-list/redhat` is actually used, you want to clone a part of it to save disk space. So, there is a sparse checkout. In particular, `sparse-checkout` has been added in Git 2.25.

I would like to use this feature to speed up `fetch redhat` and reduce the disk size of `vuln-list`.

**NOTE: If you are using less than Git 2.25, will be the same operation as before.**

## Verification
```
$ lscpu | grep "Model name"
Model name:                      Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
```

By introducing sparse checkout, gost succeeded in compressing the clone time by about 4 times and the disk size by about 20 times.

|                 | clone time | disk size |
|:---------------:|:----------:|:---------:|
|   gost 539d142  |    1m56s   |    3.6G   |
| sparse checkout |     30s    |    183M   |

### log
- sparse checkout
```console
$ gost fetch redhat --debug
DBUG[05-25|06:39:43] remove an existed directory 
DBUG[05-25|06:40:10] Failed to fetch the CVE details.         err=nil
DBUG[05-25|06:40:10] Red Hat updated files: %d                LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[05-25|06:40:13] Insert RedHat into DB                    db=sqlite3
...

$ du -h vuln-list | tail -n 1
183M	vuln-list
```

- gost 539d142
```console
$ gost fetch redhat --debug
DBUG[05-25|06:36:28] remove an existed directory 
DBUG[05-25|06:38:19] Failed to fetch the CVE details.         err=nil
DBUG[05-25|06:38:19] Red Hat updated files: %d                LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[05-25|06:38:24] Insert RedHat into DB                    db=sqlite3
...

$ du -h vuln-list | tail -n 1
3.6G	vuln-list
```

## Reference
- https://github.blog/2020-01-13-highlights-from-git-2-25/
- https://git-scm.com/docs/git-sparse-checkout

### CODE REVIEW

**Comment by MaineK00n** [comment]
## Verification
It has been tested with git version: 2.23.1, 2.25.0, and 2.31.1.
Using the following Dockerfile and docker tag function, you should be able to reproduce a variety of git environments.

```Dockerfile
FROM golang:1.16.4 as builder

RUN apt update \
    && apt install -y git make gcc musl-dev \
    && rm -rf /var/lib/apt/lists/*
RUN git clone -b support-sparse-checkout https://github.com/MaineK00n/gost.git
RUN cd gost && make install

FROM ubuntu:latest

ARG GIT_VER="2.31.1"

RUN apt update \
    && apt install -y libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake gcc \
    && rm -rf /var/lib/apt/lists/*
RUN apt update \
    && apt install -y ca-certificates --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN curl -o git.tar.gz https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.gz
RUN tar -zxf git.tar.gz
RUN cd git-* && make prefix=/usr/local all && make prefix=/usr/local install

COPY --from=builder /go/bin/gost /usr/local/bin/
```

```console
$ docker build -t gost-test:2.31.1 --build-arg GIT_VER=2.31.1 --no-cache .
$ docker run -it --rm gost-test:2.31.1 /bin/bash -c "git --version && gost fetch redhat --debug"
```

### Result
- git version: < 2.25
```console
// clone vuln-list command
// $ git clone --depth=1 https://github.com/aquasecurity/vuln-list.git

root@01a0fe04ab98:/# git --version
git version 2.23.1
root@01a0fe04ab98:/# gost fetch redhat --debug
DBUG[05-25|18:32:21] remove an existed directory 
DBUG[05-25|18:34:19] Failed to fetch the CVE details.         err=nil
DBUG[05-25|18:34:19] Red Hat updated files: %d                LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[05-25|18:34:25] Insert RedHat into DB                    db=sqlite3
```

- git version: >= 2.25.0, < 2.27.0

```console
// clone vuln-list command
// $ git clone --depth 1 --filter=blob:none --no-checkout git@github.com:aquasecurity/vuln-list.git 
// $ git --git-dir vuln-list/.git --work-tree vuln-list sparse-checkout init --cone
// $ git --git-dir vuln-list/.git --work-tree vuln-list sparse-checkout set redhat

root@e395c6eeee0c:/# git --version
git version 2.25.0
root@e395c6eeee0c:/# gost fetch redhat --debug
DBUG[05-25|18:42:53] remove an existed directory 
DBUG[05-25|18:43:11] Failed to fetch the CVE details.         err=nil
DBUG[05-25|18:43:11] Red Hat updated files: %d                LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[05-25|18:43:15] Insert RedHat into DB                    db=sqlite3
```

- git version: >= 2.27.0
```console
// clone vuln-list command
// $ git clone --depth 1 --filter=blob:none --sparse git@github.com:aquasecurity/vuln-list.git
// $ git --git-dir vuln-list/.git --work-tree vuln-list sparse-checkout init --cone
// $ git --git-dir vuln-list/.git --work-tree vuln-list sparse-checkout set redhat

root@61619a44446f:/# git --version
git version 2.31.1
root@61619a44446f:/# gost fetch redhat --debug
DBUG[05-25|18:55:33] remove an existed directory 
DBUG[05-25|18:55:51] Failed to fetch the CVE details.         err=nil
DBUG[05-25|18:55:51] Red Hat updated files: %d                LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[05-25|18:55:54] Insert RedHat into DB                    db=sqlite3
```

**Review by kotakanbe — APPROVED** [review]
LGTM

**Comment by kotakanbe** [comment]
before

```
$ git --version
git version 2.17.1
ubuntu@dev  ~│g│s│g│k│gost  ⎇ 63~  du -hs vuln-list/*
11M     vuln-list/alpine
17M     vuln-list/amazon
4.0K    vuln-list/CONTRIBUTING.md
313M    vuln-list/cvrf
3.9M    vuln-list/cwe
133M    vuln-list/debian
31M     vuln-list/ghsa
40M     vuln-list/glad
1.3M    vuln-list/go
4.0K    vuln-list/last_updated.json
1019M   vuln-list/nvd
1.4G    vuln-list/oval
32M     vuln-list/photon
4.0K    vuln-list/README.md
110M    vuln-list/redhat
230M    vuln-list/ubuntu
```

after

```
ubuntu@dev  ~│g│s│g│k│gost  ⎇ 63~  git --version
git version 2.32.0
ubuntu@dev  ~│g│s│g│k│gost  ⎇ 63~  du -hs vuln-list/*
4.0K    vuln-list/CONTRIBUTING.md
4.0K    vuln-list/last_updated.json
4.0K    vuln-list/README.md
110M    vuln-list/redhat
```

**Comment by kotakanbe** [comment]
I ran the integration test and confirmed that there is no difference in the results from master.

**Pull request merged**
